#!/usr/bin/env node
'use strict';

// ─── SETUP ─────────────────────────────────────────────────────────────────
const StyleDictionary = require('style-dictionary');

// ─── PARSER: normalize DTCG ($value/$type) → Style Dictionary (value/type) ─
// Primitives use DTCG format, semantics use SD v2 format — this unifies both.
StyleDictionary.registerParser({
  pattern: /\.json$/,
  parse: ({ contents }) => normalize(JSON.parse(contents)),
});

// Keys to strip at the root level of each token file — these are file-level metadata,
// not tokens, and cause "Property Value Collision" warnings when SD merges all files.
const ROOT_META_KEYS = new Set(['$schema', '$metadata', '_note']);

function normalize(obj, depth = 0) {
  if (Array.isArray(obj)) return obj.map(o => normalize(o, depth));
  if (typeof obj !== 'object' || !obj) return obj;
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (depth === 0 && ROOT_META_KEYS.has(k)) continue;
    const nk = k === '$value' ? 'value' : k === '$type' ? 'type' : k;
    out[nk] = normalize(v, depth + 1);
  }
  return out;
}

// ─── TRANSFORM: set token.attributes.level from path root ──────────────────
// Enables file-level filtering: primitives / semantic / component
StyleDictionary.registerTransform({
  name: 'attribute/level',
  type: 'attribute',
  transformer: (token) => {
    const root = token.path[0];
    return {
      level: root === 'primitive' ? 'primitive'
           : root === 'semantic'  ? 'semantic'
           : 'component',
    };
  },
});

// Tokens whose last path segment starts with '_' are documentation stubs, not tokens.
const isReadme = t => t.path.some(p => String(p).startsWith('_'));

// ─── TRANSFORM: component-level tokens get --agtc-component-* prefix ───────
// Standard name/cti/kebab generates --agtc-button-primary-background but components
// expect --agtc-component-button-primary-background. This transform corrects that.
StyleDictionary.registerTransform({
  name: 'name/agtc/prefixed',
  type: 'name',
  transformer: (token, options) => {
    const prefix = options?.prefix || '';
    const base = token.path.join('-');
    if (token.attributes?.level === 'component') {
      return prefix ? `${prefix}-component-${base}` : `component-${base}`;
    }
    return prefix ? `${prefix}-${base}` : base;
  },
});

StyleDictionary.registerTransformGroup({
  name: 'css/agtc',
  transforms: ['attribute/level', 'attribute/cti', 'name/agtc/prefixed', 'time/seconds', 'content/icon', 'size/rem', 'color/css'],
});

// ─── FORMAT: CSS dark mode — [data-theme="dark"] wrapper ───────────────────
// Generates only the dark overrides (deltas vs. light mode).
// Loaded after all.css: light variables are redefined for the dark selector.
StyleDictionary.registerFormat({
  name: 'css/dark-mode',
  formatter: ({ dictionary }) => {
    const vars = dictionary.allTokens
      .filter(t => !isReadme(t))
      .map(t => `  --${t.name}: ${t.value};`)
      .join('\n');
    return [
      '/* Generated by Agentica Style Dictionary — dark mode overrides — do not edit manually */',
      '[data-theme="dark"] {',
      vars,
      '  color-scheme: dark;',
      '}',
      '',
    ].join('\n');
  },
});

// ─── FORMAT: Tailwind CSS config extension ──────────────────────────────────
// Outputs a JS module ready to spread into tailwind.config.js > theme.extend
StyleDictionary.registerFormat({
  name: 'tailwind/config',
  formatter: ({ dictionary }) => {
    const colors = {};
    const spacing = {};
    const borderRadius = {};

    dictionary.allTokens
      .filter(t => t.attributes?.level === 'semantic' && !isReadme(t))
      .forEach(t => {
        const key   = 'agtc-' + t.path.slice(1).join('-');
        const value = `var(--${t.name})`;

        if (t.type === 'color') {
          colors[key] = value;
        } else if (t.type === 'dimension') {
          if (t.path.some(p => p === 'space' || p === 'spacing')) spacing[key] = value;
          else if (t.path.some(p => p === 'radius'))               borderRadius[key] = value;
        }
      });

    return [
      '// Generated by Agentica Style Dictionary — do not edit manually',
      '// Requires dist/tokens/css/all.css to be loaded for var() to resolve.',
      '//',
      '// tailwind.config.js:',
      '//   import agtc from "@agentica-ds/tokens/tailwind";',
      '//   export default { theme: { extend: agtc } };',
      '',
      `export default ${JSON.stringify({ colors, spacing, borderRadius }, null, 2)};`,
    ].join('\n');
  },
});

// ─── FORMAT: Material Angular M3 SCSS theme ────────────────────────────────
// Maps Radix tonal steps (1-12) to M3 tonal palette stops (0-100).
// Lighter steps = higher M3 values: Radix 1 ≈ M3 99, Radix 12 ≈ M3 0.
StyleDictionary.registerFormat({
  name: 'material-angular/m3-theme',
  formatter: ({ dictionary }) => {
    const radixToM3 = { 1: 99, 2: 95, 3: 90, 4: 80, 5: 70, 6: 60, 7: 50, 8: 40, 9: 30, 10: 20, 11: 10, 12: 0 };

    const lines = [
      '// Generated by Agentica Style Dictionary — do not edit manually',
      '// Requires dist/tokens/css/all.css for var() references to resolve.',
      '//',
      '// angular.component.scss or theme.scss:',
      '//   @use "path/to/m3-theme" as *;',
      '//   @use "@angular/material" as mat;',
      '//   $theme: mat.define-theme((',
      '//     color: (primary: mat.$cyan-palette, theme-type: light),',
      '//   ));',
      '//   // Then override with $agtc-* SCSS vars where needed.',
      '',
    ];

    // Build palette maps from primitive color tokens
    const palettes = {};
    dictionary.allTokens
      .filter(t => t.attributes?.level === 'primitive' && t.type === 'color' && !isReadme(t))
      .forEach(t => {
        const [, , palette, step] = t.path;
        if (!palette || !step || step === '_readme') return;
        if (!palettes[palette]) palettes[palette] = {};
        palettes[palette][step] = t.value;
      });

    // M3 role → Radix palette mapping (teal=primary, red=error, gray=neutral)
    const roleMap = [
      ['primary',  'teal'],
      ['error',    'red'],
      ['neutral',  'gray'],
      ['secondary','accent'],
    ];

    for (const [m3Role, radixPalette] of roleMap) {
      if (!palettes[radixPalette]) continue;
      lines.push(`// ${radixPalette} → M3 ${m3Role}`);
      lines.push(`$agtc-${m3Role}-palette: (`);
      const sorted = Object.entries(palettes[radixPalette])
        .filter(([step]) => !isNaN(parseInt(step)))
        .sort(([a], [b]) => parseInt(a) - parseInt(b));
      for (const [step, rawValue] of sorted) {
        const m3Stop = radixToM3[parseInt(step)];
        if (m3Stop === undefined) continue;
        lines.push(`  ${m3Stop}: ${rawValue},`);
      }
      lines.push(');');
      lines.push('');
    }

    lines.push('// Semantic aliases — reference CSS vars for component-level overrides');
    dictionary.allTokens
      .filter(t => t.attributes?.level === 'semantic' && !isReadme(t))
      .forEach(t => {
        lines.push(`$agtc-${t.path.slice(1).join('-')}: var(--${t.name});`);
      });

    return lines.join('\n');
  },
});

// ─── BUILD ─────────────────────────────────────────────────────────────────
const sd = StyleDictionary.extend({
  source: ['tokens/primitives.json', 'tokens/semantic.json', 'tokens/component.json'],

  platforms: {
    // ── CSS: one file per level ─────────────────────────────────────────────
    css: {
      transformGroup: 'css/agtc',
      prefix: 'agtc',
      buildPath: 'dist/tokens/css/',
      files: [
        {
          destination: 'primitives.css',
          format: 'css/variables',
          filter: t => t.attributes?.level === 'primitive' && !isReadme(t),
        },
        {
          destination: 'semantic.css',
          format: 'css/variables',
          options: { outputReferences: true },
          filter: t => t.attributes?.level === 'semantic' && !isReadme(t),
        },
        {
          destination: 'components.css',
          format: 'css/variables',
          options: { outputReferences: true },
          filter: t => t.attributes?.level === 'component' && !isReadme(t),
        },
        {
          destination: 'all.css',
          format: 'css/variables',
          options: { outputReferences: true },
          filter: t => !isReadme(t),
        },
      ],
    },

    // ── JavaScript ES6 ──────────────────────────────────────────────────────
    js: {
      transformGroup: 'js',
      buildPath: 'dist/tokens/js/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
          filter: t => !isReadme(t),
        },
      ],
    },

    // ── Tailwind CSS extension ───────────────────────────────────────────────
    tailwind: {
      transformGroup: 'css/agtc',
      prefix: 'agtc',
      buildPath: 'dist/tokens/tailwind/',
      files: [
        {
          destination: 'tokens.js',
          format: 'tailwind/config',
        },
      ],
    },

    // ── Material Angular M3 SCSS ─────────────────────────────────────────────
    angular: {
      transformGroup: 'css/agtc',
      prefix: 'agtc',
      buildPath: 'dist/tokens/angular/',
      files: [
        {
          destination: '_m3-theme.scss',
          format: 'material-angular/m3-theme',
        },
      ],
    },

    // ── iOS Swift ───────────────────────────────────────────────────────────
    ios: {
      transformGroup: 'ios-swift',
      buildPath: 'dist/tokens/ios/',
      files: [
        {
          destination: 'AgenticaTokens.swift',
          format: 'ios-swift/class.swift',
          className: 'AgenticaTokens',
          filter: t => !isReadme(t),
        },
      ],
    },

    // ── Android XML ─────────────────────────────────────────────────────────
    android: {
      transformGroup: 'android',
      buildPath: 'dist/tokens/android/',
      files: [
        {
          destination: 'tokens.colors.xml',
          format: 'android/colors',
          filter: t => !isReadme(t),
        },
        {
          destination: 'tokens.dimens.xml',
          format: 'android/dimens',
          filter: t => !isReadme(t),
        },
      ],
    },
  },
});

sd.buildAllPlatforms();

// ─── BUILD 2: dark mode overrides ──────────────────────────────────────────
// Source: tokens/semantic.dark.json only (deltas vs. light mode).
// Output: dist/tokens/css/dark.css under [data-theme="dark"].
// Loaded after all.css in Storybook and consumers — light variables are
// redefined only for the dark selector.
const sdDark = StyleDictionary.extend({
  source: ['tokens/semantic.dark.json'],
  platforms: {
    'css-dark': {
      transformGroup: 'css/agtc',
      prefix: 'agtc',
      buildPath: 'dist/tokens/css/',
      files: [
        {
          destination: 'dark.css',
          format: 'css/dark-mode',
          filter: t => !isReadme(t),
        },
      ],
    },
  },
});

sdDark.buildAllPlatforms();

console.log('\n✓ Agentica tokens build complete');
console.log('  dist/tokens/css/       — CSS custom properties (primitives / semantic / components / all)');
console.log('  dist/tokens/js/        — JavaScript ES6 exports');
console.log('  dist/tokens/tailwind/  — Tailwind config extension');
console.log('  dist/tokens/angular/   — Material Angular M3 SCSS');
console.log('  dist/tokens/ios/       — Swift');
console.log('  dist/tokens/android/   — Android XML');
